kurumsal/Controllers/admin/AdminServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using dentexpert.Models;

namespace dentexpert.Controllers.admin
{
    [Authorize]

    public class AdminServicesController : Controller
    {
        private dentexpertDBEntities db = new dentexpertDBEntities();

        // GET: AdminServices
        public ActionResult Index()
        {
            return View(db.Services.ToList());
        }

        // GET: AdminServices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Services services = db.Services.Find(id);
            if (services == null)
            {
                return HttpNotFound();
            }
            return View(services);
        }

        // GET: AdminServices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminServices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,title,description,image")] Services services)
        {

            if (ModelState.IsValid)
            {
                if (Request.Files.Count > 0)
                {
                    string filename = Path.GetFileName(Request.Files[0].FileName);
                    string extn = Path.GetExtension(Request.Files[0].FileName);
                    string url = "/images/services/" + filename + extn;
                    Request.Files[0].SaveAs(Server.MapPath(url));
                    services.image = "/images/services/" + filename + extn;

                }

                db.Services.Add(services);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(services);
        }

        // GET: AdminServices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Services services = db.Services.Find(id);
            if (services == null)
            {
                return HttpNotFound();
            }
            return View(services);
        }

        // POST: AdminServices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,description,image")] Services services)
        {
            if (ModelState.IsValid)
            {
                if (Request.Files.Count > 0)
                {
                    string filename = Path.GetFileName(Request.Files[0].FileName);
                    string extn = Path.GetExtension(Request.Files[0].FileName);
                    string url = "/images/services/" + filename + extn;
                    Request.Files[0].SaveAs(Server.MapPath(url));
                    services.image = "/images/services/" + filename + extn;

                }
                var updt = db.Services.Find(services.id);
                updt.title = services.title;
                updt.description = services.description;
                updt.image = services.image;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(services);
        }

        // GET: AdminServices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Services services = db.Services.Find(id);
            if (services == null)
            {
                return HttpNotFound();
            }
            return View(services);
        }

        // POST: AdminServices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Services services = db.Services.Find(id);
            db.Services.Remove(services);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

kurumsal/Views/AdminServices/Create.cshtml
@model dentexpert.Models.Services

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h2>Hizmet Oluştur</h2>

        @using (Html.BeginForm("Create", "AdminServices", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <label>Başlık</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                   <label>İçerik</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label>Foto</label>
                    <div class="col-md-10">
                        <input type="file" name="image" class="form-control" />
                        @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Oluştur" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Geri Dön", "Index")
        </div>
    </div>
    <div class="col-md-3"></div>
</div>

kurumsal/Views/AdminServices/Delete.cshtml
@model dentexpert.Models.Services

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h3>Silmek istediğinize emin misiniz?</h3>
        <div>
            <h4>Services</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    <label>Başlık</label>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.title)
                </dd>

                <dt>
                    <label>İçerik</label>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.description)
                </dd>

                <dt>
                    <label>Foto</label>
                </dt>

                <dd>
                    <img src="@Model.image" width="50" height="50" />
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Sil" class="btn btn-default" /> |
                    @Html.ActionLink("Geri Dön", "Index")
                </div>
            }
        </div>

    </div>
    <div class="col-md-3"></div>
</div>

kurumsal/Views/AdminServices/Details.cshtml
@model dentexpert.Models.Services

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h2>Detay</h2>
        <div>

            <dl class="dl-horizontal table-bordered">
                <dt>
                   <label>Başlık</label>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.title)
                </dd>

                <dt>
                    <label>İçerik</label>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.description)
                </dd>

                <dt>
                    <label>Foto</label>
                </dt>

                <dd>
                    <img src="@Model.image" width="50" height="50"/>
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Düzenle", "Edit", new { id = Model.id }) |
            @Html.ActionLink("Geri Dön", "Index")
        </p>

    </div>
    <div class="col-md-3"></div>
</div>

kurumsal/Views/AdminServices/Edit.cshtml
@model dentexpert.Models.Services

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">

        <h2>Düzenle</h2>

        @using (Html.BeginForm("Edit", "AdminServices", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.id)

                <div class="form-group">
                    @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="image" class="form-control"/>
                        @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Düzenle" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Geri Dön", "Index")
        </div>

    </div>
    <div class="col-md-3"></div>
</div>

kurumsal/Views/AdminServices/Index.cshtml
@model IEnumerable<dentexpert.Models.Services>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h2>Hizmetler</h2>

        <p>
            @Html.ActionLink("Hizmet Oluştur", "Create")
        </p>
        <table class="table table-bordered">
            <tr>
                <th>
                    <label>Başlık</label>
                </th>
                <th>
                  <label>İçerik</label>
                </th>
                <th>
                   <label>Foto</label>
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.title)
                    </td>
                    <td>
                        @if (item.description.Length>50)
                        {
                    <p>...</p>
                }
                else
                {
                    @item.description
                }
                    </td>
                    <td>
                        <img src="@item.image" width="50" height="50"/>
                    </td>
                    <td>
                        @Html.ActionLink("Düzenle", "Edit", new { id = item.id }) |
                        @Html.ActionLink("Detay", "Details", new { id = item.id }) |
                        @Html.ActionLink("Sil", "Delete", new { id = item.id })
                    </td>
                </tr>
            }

        </table>

    </div>
    <div class="col-md-3"></div>
</div>