kurumsal/Controllers/admin/AdminAboutController.cs
using dentexpert.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace dentexpert.Controllers.admin
{
    [Authorize]
    public class AdminAboutController : Controller
    {
        dentexpertDBEntities db = new dentexpertDBEntities();
        public ActionResult Index()
        {
            var about = db.About.ToList();
            return View(about);
        }
        [HttpGet]
        public ActionResult Update(int id)
        {
            var updt = db.About.Find(id);
            return View("Update", updt);
        }

        [HttpPost]
        public ActionResult Update(About p)
        {
            if (Request.Files.Count > 0)
            {
                string filename = Path.GetFileName(Request.Files[0].FileName);
                string extn = Path.GetExtension(Request.Files[0].FileName);
                string url = "/images/about/" + filename + extn;
                Request.Files[0].SaveAs(Server.MapPath(url));
                p.image = "/images/about/" + filename + extn;
            }
                var updt = db.About.Find(p.id);
                updt.title = p.title;
                updt.description = p.description;
                updt.image = p.image;
                db.SaveChanges();
                return RedirectToAction("Index");


        }

    }
}

kurumsal/Views/AdminAbout/Index.cshtml
@model List<dentexpert.Models.About>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-2"></div>

    <div class="col-md-8">
        <table class="table table-bordered mt-5">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Başlık</th>
                    <th>Açıklama</th>
                    <th>Foto</th>
                    <th>Düzenle</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tbody>
                    <tr>
                        <td>@item.id</td>
                        <td>@item.title</td>
                        <td>
                            @if (item.description.Length > 50)
                            {
                                <p>...</p>
                            }
                            else
                            {
                                @item.description
                            }
                        </td>
                        <td>
                            <img src="@item.image" width="50" height="50" />
                        </td>
                        <td><a href="/AdminAbout/Update/@item.id" class="btn btn-info">Düzenle</a></td>
                    </tr>
                </tbody>
            }
        </table>
    </div>
    <div class="col-md-2"></div>
</div>

kurumsal/Views/AdminAbout/Update.cshtml
@model dentexpert.Models.About
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h2>Düzenle</h2>
        @using (Html.BeginForm("Update", "AdminAbout", FormMethod.Post, new { enctype = "multipart/form-data"
        }))
        {
        <div>
            <label>Başlık</label>
            @Html.TextAreaFor(m => m.title, new { @class = "form-control" })
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div>
            <label>İçerik</label>
            @Html.TextAreaFor(m => m.description, new { @class = "form-control" })
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div>
            <label>Foto</label>
            <input type="file" name="image" class="form-control"/>
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div>
            <button class="btn btn-info">
                <span>Düzenle</span>
            </button>
        </div>
        }
    </div>
    <div class="col-md-3"></div>
</div>